services:
  - type: web
    name: attendance-marking-system
    runtime: node
    plan: free
    buildCommand: |
      npm install
      python3 -m pip install --upgrade pip setuptools wheel
      python3 -m pip install --user opencv-python-headless==4.8.1.78 dlib-binary==19.24.2 face-recognition==1.3.0 numpy==1.24.3 || \
      python -m pip install --user opencv-python-headless==4.8.1.78 dlib-binary==19.24.2 face-recognition==1.3.0 numpy==1.24.3 || \
      echo "Python packages installation completed with warnings"
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: "true"
      - key: PYTHONPATH
        value: "/opt/render/project/src/.local/lib/python3.9/site-packages:/opt/render/project/src/.local/lib/python3.8/site-packages"
    autoDeploy: true 